import type { Metadata } from "next";
import { Archivo, Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import StoreWrapper from "@/store/redux/store-wrapper";

const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({subsets: ["latin"]})
const robotoMono = Roboto_Mono({subsets: ['latin']})

const fonts = {
  inter: inter,
  archivo:archivo,
  robotoMono: robotoMono
}

export const metadata: Metadata = {
  title: "Suganth Portfolio",
  description: "Generated by Raj",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <StoreWrapper>
          {children}
        </StoreWrapper>
      </body>
    </html>
  );
}
